spring:
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sottie
    username: 'sottie'
    password: 'sottie123!'
    # JPA
    jpa:
      hibernate.ddl-auto: none
      generate-ddl: false
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          format_sql: true
  mvc:
    view:
      prefix: src/main/resources/templates/
      subfix: .html

sns:
  naver:
    client:
      id: 5M4LzrK8Xu9tEjVl7HZq
      secret: tyWLI8HoDC